### ISSUE TITLE
how to get the rib of yabgp 

### ISSUE THREAD

**Issue by wuwenhao2000** [smartbgp/yabgp#78]
hello,
in the yabgp.ini, it has the option that following, my question is how to get the rib of yabgp using GET？

**_Whether maintain bgp rib table
rib = True_**

**Comment by xiaopeng163** [comment]
Hi @wuwenhao2000 

I am sorry, yabgp does not support that now, if you want to maintain rib like adj-in, please write your own handler to do that.

You can reference this doc http://yabgp.readthedocs.io/en/latest/extension.html about how to write your own yabgp.

more detail,  because through the method `update_received`  you can get all the update and withdraw messages received from the peer, so it's easy to create a rib table here.

**Comment by wuwenhao2000** [comment]
I see, thanks very much.
Currently, I am using MySQL to store the update message received.
The following is what I have done, a little ugly but which is working well 😆, I appreciate your job
https://github.com/wuwenhao2000/BGP-Agent-test

**Comment by xiaopeng163** [comment]
ok, good to know that.

If you have huge amount of BGP prefixes in your network, I suggest:

1. write bgp update message to file on local disk (by default we do that)
2. write another program to read the file and then insert/update them into MySQL

The reason is, if you insert/update prefix in `update_received` each time, it will slow down the yabgp main process. So asynchronous mode like file write/read will be better.

**Comment by wuwenhao2000** [comment]
I see thanks a lot
